c-morris/BGPExtrapolator

AS.cpp
Announcement.h
Extrapolator.cpp
main.cpp

I did some reading on iostreams and these simple changes have increased the csv writing speed from roughly 2.5 MB/sec to 30 MB/sec. I tested these changes and they don't appear to break anything. 
Let me know if you have any suggestions for changes, otherwise merge this into master when you're ready.

Change CSV output to be about 10x faster

---

AS.cpp

Tiny bug I discovered when subclassing AS int ROVppAS.

fix delegate constructor in AS.cpp

---

ROVppAS.cpp
ROVppAS.h
ROVppExtrapolator.cpp
ROVppTest.cpp

Implementation of 0.2bis, where blackholes are only sent to customers. The integer 5 in the database corresponds to this policy. 
Also some unit test fixes.

ROV++ 0.2bis

---

ROVppExtrapolator.cpp

Traceback is back and better than ever. 
Now that we have the alt flag set for preventive announcements, we only do traceback when the alt flag is set.

Re-enabling loop detection for 0.3

---

ASTest.cpp
Announcement.h
AnnouncementTest.cpp
Extrapolator.cpp
ROVppAnnouncement.h
ROVppExtrapolator.cpp
ROVppTest.cpp

Preliminary implementation of full path annoucements. It only handles seeding at the origin (shouldnt be a problem for now). It is slightly modified from my verification version, appending the current asn in send_all_announcements(). 
Keep in mind the path is stored in REVERSE ORDER, {origin->cur_asn}. It is much more efficient to operate on the end of the vector than the front, though we can adjust this if it is a problem.

Preliminary full path implementation

---

include/ASes/BaseAS.h
include/Logger.h
include/Prefix.h
include/Tests/Tests.h
main.cpp
src/ASes/BaseAS.cpp
src/ASes/ROVppAS.cpp
src/Extrapolators/BlockedExtrapolator.cpp
src/Logger.cpp
src/Tests/Tests.cpp

Fix a few small things. 
- Correct the data type of i in ROVppAS.cpp (this generated a compiler warning because of a comparison between signed and unsigned integers)
- Rewrite the less than operator for Prefixes so it is more readable and more efficient
- Delete an unnecessary ternary operator in BaseAS.cpp
- Comment out the broken ROVpp test with a note to uncomment it once it is fixed.

Minor Code Improvements

---

include/ASes/BaseAS.h
include/ASes/ROVppAS.h
src/ASes/BaseAS.cpp
src/ASes/ROVppAS.cpp

Moved `tiny_hash()` to BaseAS class. Also, updated `BaseAS::get_random()` implementation to utilize `tiny_hash()`

BaseAS tiny_hash

---

main.cpp

Added new command line arguments for enabling logging into the console, specifying path to a log folder, and choosing severity of errors to be logged. After parsing, they are passed to `Logger::init_logger`

Log parameters

---

include/Extrapolators/BaseExtrapolator.h
include/Extrapolators/Extrapolator.h
include/Tests/Tests.h
main.cpp
src/Extrapolators/BaseExtrapolator.cpp
src/Extrapolators/BlockedExtrapolator.cpp
src/Extrapolators/Extrapolator.cpp
src/SQLQueriers/SQLQuerier.cpp
src/Tests/ExtrapolatorTest.cpp
src/Tests/Tests.cpp

Saving the results of the Extrapolator is the second most time consuming operation it does (propagation is the most time consuming). Speedups here will have a significant impact on the overall runtime, and fortunately it is pretty straightforward to parallelize. 
Timing tests on the mrt_small input table showed a 30% speedup for non-inverted results. 
Credit to jfuruness for suggesting this improvement.

Multithreaded Results Saving

---

include/Extrapolators/BaseExtrapolator.h
src/ASes/AS.cpp
src/Tests/ExtrapolatorTest.cpp

A few things that got missed in the merging. 
- The AS ostream operator needs to be templated
- Missing semaphore and thread includes when compiling for test
- Extrapolator initialization updated in results saving test with new signature

Hotfix from simultaneous merges

---

include/Extrapolators/BlockedExtrapolator.h
include/Tests/Tests.h
main.cpp
src/Extrapolators/BlockedExtrapolator.cpp
src/Tests/ExtrapolatorTest.cpp
src/Tests/Tests.cpp

Now, by default, when an AS in multihomed, the extrapolator propagates its announcement to providers if there are some that haven't received an announcement from that prefix with origin = current multihomed AS. Multihomed ASes also propagate to peers in that mode. I also created tests for the new mode.

Automatic multihomed mode

---

include/Tests/Tests.h
src/Extrapolators/BlockedExtrapolator.cpp
src/Extrapolators/ROVppExtrapolator.cpp
src/Tests/ExtrapolatorTest.cpp
src/Tests/ROVppTests.cpp
src/Tests/Tests.cpp

I fixed prepending behavior in those extrapolators and created a bunch of tests for it.
give_ann_to_as_path in both Blocked and ROV++ extrapolators now compares priority when there are announcements with the same prefix and timestamp.

Prepending in Blocked and ROV++ extrapolators

---

include/Prefix.h
main.cpp
src/Extrapolators/BaseExtrapolator.cpp
src/Extrapolators/BlockedExtrapolator.cpp
src/Extrapolators/EZExtrapolator.cpp
src/Extrapolators/ROVppExtrapolator.cpp
src/Graphs/BaseGraph.cpp
src/Logger.cpp
src/SQLQueriers/ROVppSQLQuerier.cpp
src/SQLQueriers/SQLQuerier.cpp

Changed the code to use Logger instead of `cout` and `cerr`. Tests still use normal console output instead of Logger.
Added `boost::log::keywords::auto_flush = true` argument to `boost::log::add_console_log()` in Logger.cpp. That way it flushes the buffers after each log record is written

Use Logger instead of cout and cerr

---

include/Extrapolators/BaseExtrapolator.h
src/Extrapolators/BaseExtrapolator.cpp

The Announcement passed into stream_as_path should have been a copy, not a reference.

Fix received_from_asn in stream_as_path 

---

src/Extrapolators/BaseExtrapolator.cpp

Inverse and default results were written to the same file. Attempting to save both inverse and default results caused an error during saving to the database because it tried inserting default results into the inverse table.

Save inverse results to a separate file in save_results_thread

---

include/Extrapolators/BaseExtrapolator.h
include/Extrapolators/BlockedExtrapolator.h
include/Extrapolators/EZExtrapolator.h
include/Extrapolators/Extrapolator.h
include/Extrapolators/ROVppExtrapolator.h
main.cpp
src/Extrapolators/BaseExtrapolator.cpp
src/Extrapolators/EZExtrapolator.cpp
src/Extrapolators/Extrapolator.cpp
src/Extrapolators/ROVppExtrapolator.cpp
src/Tests/ExtrapolatorTest.cpp
src/Tests/ROVppTests.cpp

Added a command line parameter to specify a maximum number of worker threads. The value is passed to all extrapolators even though we don't use it in the ROVpp version. Maybe in the future there will be multithreading too.

Add max_threads parameter

---

ROVppExtrapolator.cpp

Issue_ID: 6
Location: ROVppExtrapolator::give_ann_to_as_path() Lines 226 - 233
Bug: In superprefix attacks (or other attacks where the attacker is
producing an announcement with an unknown roa_validity) the optimization
flag for NOTHIJACKED is applied to the superprefix (i.e. the unknown
roa_validity announcement). It should be given the HIJACKED optimization
flag instead (Right?)
Cause: There's a logical check for assigning the optimization flag that
applies it solely on the roa_validity value, when it should also
consider whether or not it's the attacker or not.
Expected Impact: Doesn’t affect results since the most specific prefix
will always be chosen, however, should be fixed for cases where the
hijack may have an unknown roa validity (which we currently do not have)
Discussed: yes …

Fix for Issue_ID 6

---

ROVppAS.cpp

**Location**: Unknown, probably best_alternative_announcement
**Location (Updated)**: process_announcement (singular)
**Bug**: Propagation graph does not converge in a reasonable amount of time (possible route flapping?) in non-lite versions (only tested v1 and v1 lite). It’s possible that this is correct behavior, but we don't have a route-flapping test scenario (we don't have one at all actually) that validates this.
**Bug (Updated)**:  Condition to select best announcement in process_announcement used an inaccurate assumption about new announcement being processed, which caused route flapping between announcements with and without holes.
Cause: unknown (something specific to non-lite functions)
**Cause (Updated)**: incorrect assumption about new announcement being processed in …

Fix issue 17

---

include/ASes/BaseAS.h
include/ASes/ROVAS.h
include/ASes/ROVppAS.h
include/Announcements/ROVAnnouncement.h
include/Announcements/ROVppAnnouncement.h
include/Extrapolators/BaseExtrapolator.h
include/Extrapolators/ROVExtrapolator.h
include/Graphs/BaseGraph.h
include/Graphs/ROVASGraph.h
include/SQLQueriers/ROVSQLQuerier.h
include/TableNames.h
include/Tests/Tests.h
main.cpp
src/ASes/BaseAS.cpp
src/ASes/ROVAS.cpp
src/Announcements/ROVAnnouncement.cpp
src/Extrapolators/BaseExtrapolator.cpp
src/Extrapolators/BlockedExtrapolator.cpp
src/Extrapolators/ROVExtrapolator.cpp
src/Graphs/BaseGraph.cpp
src/Graphs/ROVASGraph.cpp
src/SQLQueriers/ROVSQLQuerier.cpp
src/Tests/ROVTests.cpp
src/Tests/Tests.cpp

Contains a version of extrapolator that implements ROV. Includes its own child class for Announcement, AS, and every other class.
_ROVppExtrapolator can be used only after reworking `ROVPPAS_TYPE` flags in ROVppAS.h. I changed `ROVPPAS_TYPE_ROV` from 1 to 2 to match lib_bgp_data_.

ROV reference policy

---

include/Tests/Tests.h
src/Extrapolators/BaseExtrapolator.cpp
src/Tests/ExtrapolatorTest.cpp
src/Tests/Tests.cpp

parse_path now uses a stringstream to simplify parsing of an as_path. There is also a test for this function.

Refactor parse_path and add a test

---

ROVppAS.cpp
ROVppAS.h
ROVppTest.cpp

Issue Id: 14
Location: Unknown
Bug: Fixes of other bugs reintroduced routing loops in v3
Cause: turns out the ATTACKER_ON_ROUTE_FLAG was actually a needed flag for preventive announcements to prevent the kind of loop we're noticing now. This is noted in the loop documentation we have on overleaf.
Expected Impacted: need to fix before getting additional v3 and v3 lite results
Discussed: Yes
Had to add the ATTACKER_ON_ROUTE_FLAG back in, but this time properly implemented.
It solves the loop scenario which is a saved full sim run.
Also seems that one of the unit tests was broken for a while. It was the `test_process_announcements2` test.
The return true and false were swapped. Not sure when that happened.

Fixed issue 14

---

Announcement.h
ROVppAS.cpp
ROVppExtrapolator.cpp

Issue Id: 20
Location: ROVppAS::process_anouncements, ROVppExtrapolator::send_all_announcements
Bug: Fixes of other bugs impaired the performance of v2 lite and potentially v2 (noticable in trace_hijacked_adopting)
Cause: This is caused by the special case when an attack annoucement is received from a customer. In this case we should drop the announcement and blackhole. Before it was just dropping the announcement, which created a hidden hijacks.
Expected Impacted: hijack rate is higher than all other ROV++ policies during first 60%
Discussed: Yes
Had to update the dropping of the announcement part and add filtering for blackhole&preventive announcements caused from attacking announcements from customers.

Fixed issue 20
